# Generated by Django 4.2.3 on 2023-07-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_auto_20181211_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='approved',
            field=models.BooleanField(null=True),
        ),
    ]
