# Generated by Django 4.2.3 on 2023-07-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('edit_biblio_batchmode', 'Can perform batch catalog modifications - ILS'), ('bulk_import_cover_images', 'Can bulk import local cover images - ILS'), ('bulk_import_patron_images', 'Can bulk import patron photographs - ILS'), ('backup_restore', 'Can perform system backup & restore - ILS'), ('borrow', 'Can borrow - ILS'), ('circulate_place_holds', 'Can circulate & place holds - ILS'), ('collect_fines_fees', 'Can collect fines & fees - ILS'), ('delete_anonymize_patrons', 'Can delete old borrowers - ILS'), ('edit_calendar', 'Can set calendar - ILS'), ('edit_biblio', 'Can edit catalog - ILS'), ('edit_items', 'Can edit items data - ILS'), ('edit_news', 'Can write news - ILS'), ('edit_patrons', 'Can edit performs data - ILS'), ('edit_quotations', 'Can edit quotes - ILS'), ('execute_reports', 'Can run reports - ILS'), ('bulk_export_catalog', 'Can bulk export catalog & items data - ILS'), ('force_checkout', 'Can force checkout to restricted borrowers - ILS'), ('bulk_import_catalog', 'Can bulk import catalog & items data - ILS'), ('bulk_import_patrons', 'Can bulk import patrons data - ILS'), ('edit_items_batchmode', 'Can perform batch item modifications - ILS'), ('manage_circ_rules', 'Can manage circulation rules - ILS'), ('manage_restrictions', 'Can manage account restrictions - ILS'), ('manage_system_preferences', 'Can manage system preferences - ILS'), ('moderate_comments', 'Can moderate user comments - ILS'), ('moderate_suggestions', 'Can moderate user suggestions - ILS'), ('moderate_tags', 'Can moderate user tags - ILS'), ('modify_holds_priority', 'Can modify hold priority - ILS'), ('edit_patrons_batchmode', 'Can perform batch patron modifications - ILS'), ('run_confidential_reports', 'Can run confidential reports - ILS'), ('upload_local_cover_images', 'Can upload local cover images - ILS'), ('upload_patron_images', 'Can upload patron photographs - ILS'), ('writeoff', 'Can write off fines & fees - ILS'), ('self_renew', 'Can self renew – ILS'), ('self_reserve', 'Can self reserve – ILS'), ('suggest_books', 'Can suggest books – ILS'), ('edit_genre', 'Can edit genre – ILS'), ('edit_language', 'Can edit language – ILS'), ('edit_stopwords', 'Can edit stopwords – ILS'), ('edit_authors', 'Can edit authors – ILS'), ('edit_biblioimages', 'Can_edit_biblioimages – ILS'), ('edit_rentalcharges', 'Can edit rentalcharges – ILS'), ('edit_entryexitlogs', 'Can edit entryexitlogs – ILS'), ('edit_systempreferences', 'Can edit systempreferences – ILS'))},
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, help_text='Roll number/aadhar number/employee number', max_length=16, null=True),
        ),
    ]
